# Site
repository: hasan-ali/cv
favicon: images/favicon.ico

# Personal info
name: Hassan Ali
title: Graduate Student
email: hali@bccrc.ca
website: www.github.com/hasan-ali

# Social links
twitter_username: hassanasifali
github_username:  hasan-ali
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hassan and I'm a graduate student 

  I am most skilled in: <mark>Cell Culture</mark> and <mark>Organoids</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in oncology some of my other interests and hobbies are:
   - Bicycling
   - Hiking
   - Camping
   - Food (pie)
# - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: hasan-ali/cv

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
